services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: